---
- hosts: localhost
  connection: local

  tasks:

    - name: Remove old container
      shell: docker rm -f monitor-container || true

    - name: Build Docker image
      shell: docker build -t cloudops-monitor ..

   - name: Run docker container
     shell: docker run -d --env-file /opt/cloudops/.env -p 5000:5000 --name monitor-container cloudops-monitor