---
- hosts: localhost

  tasks:

    - name: Stop old container
      shell: docker stop monitor-container || true

    - name: Remove old container
      shell: docker rm monitor-container || true

    - name: Build Docker image
      shell: docker build -t cloudops-monitor ..

    - name: Run docker container
      shell: docker run -d -p 5000:5000 --name monitor-container cloudops-monitor